### ISSUE TITLE
API endpoint returning 404 Not Found

### ISSUE THREAD

**Issue by devxbasit** [Joeljaison391/GeeksforGeeks-Profile-API#1]
**Describe the bug**
Endpoint not working

**To Reproduce**
1. Open Postman and make HttpGet request to https://gfg-api-5636a15dd742.herokuapp.com/api/profile/baatinx

**Expected behavior**
Should return user data

**Screenshots**
![image](https://github.com/user-attachments/assets/8b70a1e2-af9c-4c7f-a1b4-27938d40e5b6)

**Desktop (please complete the following information):**
XUbuntu - latest 

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by Joeljaison391** [comment]
### Solution

use  `https://worktrack.azurewebsites.net/api/profile/:username` endpoint
